### ISSUE TITLE
Can't land on any planet once launched from OverWorld and end up stuck on Galaxy map

### ISSUE THREAD

**Issue by b0bst3r** [lAimBotl/Rotary-Tech-modpack-#10]
Caused by GalaxySpace-1.1.9 STABLE.jar

Works fine with GalaxySpace-1.1.8 STABLE.jar

Be aware if the choice is to remove GS alltogether that there are scripts containing GS items.

**Comment by Bizzmark** [comment]
RT 5.5 reverts GalaxySpace to 1.1.8 as requested. Note that 1.1.9 purportedly fixes several crashes on planets - keep an eye out; hopefully these are rare.
