### ISSUE TITLE
Player skins

### ISSUE THREAD

**Issue by lilmoefow** [lAimBotl/Rotary-Tech-modpack-#4]
I believe that the funky player skins can be fixed by changing this to false in the Et Futurum config file

  B:"Skin overlays"=true

**Comment by Toperoco** [comment]
Confirmed and fixed on server

Edit: Nope, it's back..

**Comment by b0bst3r** [comment]
Maybe needs changing clientside too?

**Comment by b0bst3r** [comment]
Confirmed, changing config clientside and serverside fixes the issue.

**Comment by Bizzmark** [comment]
Fixed in 5.5 (hopefully).
