### ISSUE TITLE
Missing mods from pack

### ISSUE THREAD

**Issue by b0bst3r** [lAimBotl/Rotary-Tech-modpack-#6]
Add BC Compat 
 - Will display BC gate and chipset recipes in game
 - Will add in Apiarists Pipe for bees

Add NEI Addons
 - Will display bee produce and bee mutation NEI screens

Add Bee Better at Bees 
 - cos it adds cool looking stuff for bee breeding :)

**Comment by Bizzmark** [comment]
Added all in 5.5. Thank you, b0b.
