### ISSUE TITLE
Backpacks

### ISSUE THREAD

**Issue by Gemlord** [lAimBotl/Rotary-Tech-modpack-#7]
Don't know if this is already known to you, but the Iron Backpack's mod backpack's don't work
the actual issue can''t really be screenshotted but essentially they randomly revert their "history"
i.e. you put a stack of items in, it reverts and then you open it and it;'s empty, deleteing them, and vice versa possible you take your stack out, it reverts, and they are there to be taken again. Would suggest is replaced by another backpacks mod such as Plain ol' "Backpacks" like is on NH.

**Comment by Bizzmark** [comment]
Iron Backpacks will be removed in the next version of RT (after 5.5). Regular Backpacks mod added - everyone should be moving their precious belongings to those instead.
