### ISSUE TITLE
Please remove the $%#@#$# Weather mod

### ISSUE THREAD

**Issue by ReactivePlatypus** [lAimBotl/Rotary-Tech-modpack-#8]
A number of concerns have been brought up by server users, and I've been victim to several myself:

1. Constant lightning strikes make living in, near, or anywhere within render distance of a forest incredibly dangerous, due to massive uncontrollable forest fires breaking out with every strike. Infernal mobs are bad enough for this.
1.5. It also renders making just about anything out of wood an exercise in frustration, as you can expect to lose your roof about once an hour.
2. Tornadoes, while not actively destructive, are both incredibly annoying to work around and have been reported as causing motion sickness for some players. 
3. Large amounts of constantly-moving particles cause terrible FPS lag in singleplayer.
4. Getting insignificantly damaged by hailstorms exacerbates an existing (unfixed) issue with Reika's mods where Angel Rings randomly stop working when the player is damaged.
5. Weather 2 rain is not counted as vanilla rain, and appears to actively prevent vanilla rain from happening. Anything that is helped or hindered by rain loses that functionality.
6. It contributes no meaningful content to the pack.

**Comment by Bizzmark** [comment]
Removed by popular demand in 5.5.
